### ISSUE TITLE
Nice logo

### ISSUE THREAD

**Issue by anapaulagomes** [anapaulagomes/pardal#10]
We got a good name (😸), now we need a good logo for our [Pardal](https://en.wiktionary.org/wiki/pardal#/media/File:House_Sparrow_(M)_I_IMG_7881.jpg).

You can leave your suggestion to be voted as a comment here.

**Comment by tlubitz** [comment]
HI Ana,

I saw your talk today and thought it was cool. I couldn't get in touch though... I am pretty sick and had to leave early.

However, I'd like to help you with the project. Maybe you could get in touch via mail? You see my mail on my Github.

Looking forward,
Timo

**Comment by mirzazulfan** [comment]
Hi @anapaulagomes .. What do you think about this? if you need something else, please let me know :)
![pardal](https://user-images.githubusercontent.com/36124339/53392975-a3c22780-39cd-11e9-91f6-1b332d812d9b.png)

**Comment by Wmitrut** [comment]
You can consider it done!

**Comment by Wmitrut** [comment]
![image](https://user-images.githubusercontent.com/5539257/53658543-d0797780-3c37-11e9-9abd-a4ea94955f09.png)
It`s here, already made the PR
